// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3F4as93nC6g16Z1qjK5S9gmXQUvzObbA',
    appId: '1:751782837525:web:6d37fdcc672e858640fd1c',
    messagingSenderId: '751782837525',
    projectId: 'family-app-2025',
    authDomain: 'family-app-2025.firebaseapp.com',
    storageBucket: 'family-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp59j-sn6ScMmuuAOHjyBT3Ozyym_-fvw',
    appId: '1:751782837525:android:c7cfcc3474d82e6b40fd1c',
    messagingSenderId: '751782837525',
    projectId: 'family-app-2025',
    storageBucket: 'family-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChLDJZgGEe0Pp6epMjNGJBtHDKzlvMyVM',
    appId: '1:751782837525:ios:1e014f66ebfcf8b340fd1c',
    messagingSenderId: '751782837525',
    projectId: 'family-app-2025',
    storageBucket: 'family-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.familyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChLDJZgGEe0Pp6epMjNGJBtHDKzlvMyVM',
    appId: '1:751782837525:ios:1e014f66ebfcf8b340fd1c',
    messagingSenderId: '751782837525',
    projectId: 'family-app-2025',
    storageBucket: 'family-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.familyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3F4as93nC6g16Z1qjK5S9gmXQUvzObbA',
    appId: '1:751782837525:web:90be68073e8f996f40fd1c',
    messagingSenderId: '751782837525',
    projectId: 'family-app-2025',
    authDomain: 'family-app-2025.firebaseapp.com',
    storageBucket: 'family-app-2025.firebasestorage.app',
  );
}